# 异常 

在程序运行时，不可避免的会发生错误,合理的处理异常，可以使程序更健壮

## 分类

Error : jvm 内部错误，如内存溢出，

Exception : 因编程错误或外在因素导致的错误

```java
public static void main(String[] args) {
    int a= 10/0;
}
```

会发送异常，main方法接收到异常，导致程序终止

```bash
Exception in thread "main" java.lang.ArithmeticException: / by zero
```

## try catch finally

使用 这几个关键字处理异常，try块中是可能抛出异常的代码块, catch用于捕抓异常，可以有多个catch块，finally无论是否有异常都会执行,通过用来关闭资源

```java
try {
    int a= 10/0;
} catch (Exception e) {
    e.printStackTrace();
} finally {
    System.out.println("end");
}
```

## 声明抛出异常 throws

当前方法不处理异常，由方法的调用者处理异常，使用 `throws`关键字

```java
public class BinaryTest {

    public static void main(String[] args) {
        try {
            add();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public  static void add() throws Exception{
        int a=10/0;
    }
}
```

## 手动抛出异常 throw

当发送错误时，系统会自动创建异常对象并抛出，程序也可以自己创建异常抛出,使用`throw`关键字

```java
public class BinaryTest {

    public static void main(String[] args) {
        try {
            add();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public  static void add() throws Exception{
        
        throw  new Exception("aaa");
    }
}
```



## 自定义异常

可以自己自定义异常,通常继承`RuntimeException`

```java
public class PersonException extends RuntimeException {

    public PersonException() {
    }

    public PersonException(String message) {
        super(message);
    }
}

```



